// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqFpc4J9dSYLd75FqVvvqnfP9frtq22n4',
    appId: '1:518164761248:web:c69a4744e92518990917c5',
    messagingSenderId: '518164761248',
    projectId: 'pediapp-fe927',
    authDomain: 'pediapp-fe927.firebaseapp.com',
    storageBucket: 'pediapp-fe927.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA__N-SbQ7ffDBXym4pCE5jTDuZRPidFYM',
    appId: '1:518164761248:android:caa0d87d25f782a10917c5',
    messagingSenderId: '518164761248',
    projectId: 'pediapp-fe927',
    storageBucket: 'pediapp-fe927.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-zGSymVose_L75bLVr8h8IYTfbop4Gxk',
    appId: '1:518164761248:ios:3345eb25f24908000917c5',
    messagingSenderId: '518164761248',
    projectId: 'pediapp-fe927',
    storageBucket: 'pediapp-fe927.firebasestorage.app',
    iosBundleId: 'com.example.pediapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-zGSymVose_L75bLVr8h8IYTfbop4Gxk',
    appId: '1:518164761248:ios:3345eb25f24908000917c5',
    messagingSenderId: '518164761248',
    projectId: 'pediapp-fe927',
    storageBucket: 'pediapp-fe927.firebasestorage.app',
    iosBundleId: 'com.example.pediapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqFpc4J9dSYLd75FqVvvqnfP9frtq22n4',
    appId: '1:518164761248:web:561b5eb7f21d38910917c5',
    messagingSenderId: '518164761248',
    projectId: 'pediapp-fe927',
    authDomain: 'pediapp-fe927.firebaseapp.com',
    storageBucket: 'pediapp-fe927.firebasestorage.app',
  );
}
